* <2013-03-19 Tue 11:17>
I forgot how to use org-mode!
Ah, there we go.
Okay, the idea is to write a few scripts that will automatically create my website for me.
It will follow a similar convention to that of my current site.
** Each top level folder will be a page
*** Top level pages will have a navigation bar to link to each other
*** Within their tab, sublinks will be provided for each sub page
*** Or anchor...?
** Content will be in a separate file
** Hmm.... git?
Oh right, fix my git commit attributions.
Makes sense: I don't get credit for forks unless it gets mainlined.
It's been git-ted!
* <2013-04-19 Fri 09:49>
Was able to get 90% of what I wanted done. 
Even has a few spiffy features like being able to define variables in the content files which are replaced when generating.
Still have a few things to fix up
** Todo:
variable deliminator should be possible to escape
sub-nav bars should be able to handle anchors
make a decision about sub-sub-nav bars
make navbar float
fix WARNs
* <2013-12-19 Thu 14:36>
I want to clean this up enough so that I can actually replace my current site with it.
And I would like to do that as quickly as possible.


* <2014-02-28 Fri 12:45>
I'm going to update my website... let's see what happens
** wget the wiki from the local server
From ~/Dropbox/website/web_source/wiki
  wget -r -k -np -p -l 0 127.0.0.1/wiki/pmwiki.php --html-extension
  mv 127.0.0.1/wiki/* ./
  rm -r 127.0.0.1
** Clean up
Delete the edit pages and such
  rm *action=edit.html
  rm *action=print.html
  rm *action=diff.html
Delete most of the pdfs, but not the pictures.
  rm uploads/Background/*.pdf
  rm uploads/Research/LinuxVirtualMemoryManagement.pdf 
  rm uploads/Research/AdvancedLinuxProgramming.pdf 
Delete a lot of useless stuff (no longer need - #)
  #rm -r wiki.d/
  #rm -r wikilib.d/
  #rm -r cookbook/
  #rm -r docs/
  #rm -r local/
  #rm -r scripts/
  rm -r pub/css
  rm -r pub/guiedit/
  rm pub/index.html 
  rm -r pub/skins/print/
  rm pub/skins/index.html 
  rm -r pub/skins/pmwiki/
** Make the actual site
From ~/research/gen-site/
  make
Tar it
  tar -cvf new_site.tar ./generated/
Send to acad
  scp new_site.tar jcmarsh@acad.gwu.edu:~/
Go There, unpack into public_html, run fix_html

